import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";
import { copyFileSync, mkdirSync } from "node:fs";
import { join, resolve } from "node:path";

const banner = `/*!
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin

Papercut chess pieces by Nikolay Anzarov, licensed under CC BY 4.0.
Source: https://github.com/lichess-org/lila/tree/master/public/piece/papercut
The bundled SVGs only have non-rendering Inkscape editor metadata removed.
License: https://creativecommons.org/licenses/by/4.0/
*/`;

const prod = process.argv[2] === "production";

// Builds are portable by default and produce a complete plugin in this
// directory. Set CHESS_PLUGIN_DIR to deploy directly into a development vault.
const PROJECT_DIR = process.cwd();
const PLUGIN_OUTPUT = resolve(process.env.CHESS_PLUGIN_DIR || PROJECT_DIR);

/**
 * The bot's search runs in a Web Worker so a deep think never freezes the
 * board. Obsidian installs a single main.js, so the worker cannot ship as its
 * own file: it is bundled standalone first, then injected into the plugin as
 * a source string and turned into a Blob URL at runtime (same trick as
 * songwriter-player's analysis worker).
 */
const workerBuild = await esbuild.build({
  entryPoints: ["src/engine-worker.ts"],
  bundle: true,
  external: [...builtinModules],
  format: "iife",
  // chess.js uses BigInt literals (Zobrist hashing) internally, which need es2020+
  target: "es2020",
  logLevel: "warning",
  write: false
});
const workerSource = workerBuild.outputFiles[0].text;

const buildOptions = {
  banner: {
    js: banner,
  },
  define: {
    ENGINE_WORKER_SOURCE: JSON.stringify(workerSource)
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", ...builtinModules],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: join(PLUGIN_OUTPUT, "main.js")
};

mkdirSync(PLUGIN_OUTPUT, { recursive: true });
if (PLUGIN_OUTPUT !== resolve(PROJECT_DIR)) {
  for (const f of ["manifest.json", "styles.css", "versions.json", "THIRD_PARTY_NOTICES.md"]) {
    copyFileSync(join(PROJECT_DIR, f), join(PLUGIN_OUTPUT, f));
  }
}

if (prod) {
  await esbuild.build(buildOptions);
} else {
  const ctx = await esbuild.context(buildOptions);
  await ctx.watch();
}
