import { writeFile } from "node:fs/promises";

const BASE = "https://chess-cdn.cybercla.dev/pieces/lichess/staunty";
const pieces = { k: "K", q: "Q", r: "R", b: "B", n: "N", p: "P" };
const assets = {};

for (const color of ["w", "b"]) {
  for (const [type, letter] of Object.entries(pieces)) {
    const url = `${BASE}/${color}${letter}.svg`;
    const response = await fetch(url);
    if (!response.ok) throw new Error(`Failed to download ${url}: ${response.status}`);
    const svg = (await response.text())
      .replace(/^<\?xml[^>]*>\s*/i, "")
      .replace(/\s*<title>[\s\S]*?<\/title>\s*/i, "")
      .replace(/>\s+</g, "><")
      .trim();
    if (!svg.startsWith("<svg") || !svg.endsWith("</svg>")) {
      throw new Error(`Unexpected SVG document from ${url}`);
    }
    assets[`${color}${type}`] = `data:image/svg+xml;base64,${Buffer.from(svg).toString("base64")}`;
  }
}

const source = `// Generated by vendor-staunty.mjs. Do not edit by hand.
// Staunty chess pieces by sadsnake1, CC BY-NC-SA 4.0.
// See THIRD_PARTY_NOTICES.md.
export const STAUNTY_PIECES: Record<string, string> = ${JSON.stringify(assets, null, 2)};
`;

await writeFile(new URL("./src/staunty-assets.ts", import.meta.url), source, "utf8");
