/**
 * Vendors the bundled piece artwork into src/piece-assets.ts.
 *
 * The set is Papercut by Nikolay Anzarov, CC BY 4.0, distributed with lichess
 * (there is no separate upstream repository — see THIRD_PARTY_NOTICES.md).
 * The drawings themselves are not touched: what is stripped here is Inkscape's
 * editor state (namedview, `inkscape:`/`sodipodi:` attributes, comments), which
 * is a third of every file and draws nothing. Run with `npm run vendor`.
 */
import { writeFile } from "node:fs/promises";

const BASE = "https://raw.githubusercontent.com/lichess-org/lila/master/public/piece/papercut";
const SET_NAME = "Papercut";
const PIECES = { k: "K", q: "Q", r: "R", b: "B", n: "N", p: "P" };

/** Elements that carry meaning on screen. Their count has to survive the strip,
 *  or something that was being drawn has just been thrown away. */
function drawingCensus(svg) {
  const census = {};
  for (const [, tag] of svg.matchAll(/<([a-zA-Z][\w.:-]*)/g)) {
    // Namespaced elements are Inkscape's own (sodipodi:namedview), and the two
    // below are documentation. None of them put a pixel on the board.
    if (tag.includes(":") || tag === "metadata" || tag === "title") continue;
    census[tag] = (census[tag] ?? 0) + 1;
  }
  return JSON.stringify(census);
}

function strip(svg) {
  return svg
    .replace(/^<\?xml[^>]*>/i, "")
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/<metadata[\s\S]*?<\/metadata>/gi, "")
    .replace(/<title[\s\S]*?<\/title>/gi, "")
    // Inkscape's canvas state: window size, zoom, guides. Never rendered.
    .replace(/<sodipodi:namedview[\s\S]*?(?:\/>|<\/sodipodi:namedview>)/gi, "")
    .replace(/\s+(?:inkscape|sodipodi):[\w.-]+="[^"]*"/g, "")
    .replace(/\s+xmlns:(?:inkscape|sodipodi|svg)="[^"]*"/g, "")
    // Inkscape writes one attribute per line; the newline and its indent are
    // the only whitespace safe to collapse (path data stays untouched).
    .replace(/\s*\r?\n\s*/g, " ")
    .replace(/\s+\/>/g, "/>")
    .replace(/>\s+</g, "><")
    .trim();
}

const assets = {};
let rawBytes = 0;
let keptBytes = 0;

for (const color of ["w", "b"]) {
  for (const [type, letter] of Object.entries(PIECES)) {
    const url = `${BASE}/${color}${letter}.svg`;
    const response = await fetch(url);
    if (!response.ok) throw new Error(`Failed to download ${url}: ${response.status}`);
    const original = await response.text();
    const svg = strip(original);

    if (!svg.startsWith("<svg") || !svg.endsWith("</svg>")) {
      throw new Error(`Unexpected SVG document from ${url}`);
    }
    if (drawingCensus(original) !== drawingCensus(svg)) {
      throw new Error(`Stripping changed what ${url} draws`);
    }

    rawBytes += original.length;
    keptBytes += svg.length;
    assets[`${color}${type}`] = `data:image/svg+xml;base64,${Buffer.from(svg).toString("base64")}`;
  }
}

const source = `// Generated by vendor-pieces.mjs. Do not edit by hand.
// ${SET_NAME} chess pieces by Nikolay Anzarov, CC BY 4.0.
// See THIRD_PARTY_NOTICES.md.
export const PIECE_IMAGES: Record<string, string> = ${JSON.stringify(assets, null, 2)};
`;

await writeFile(new URL("./src/piece-assets.ts", import.meta.url), source, "utf8");
console.log(`${SET_NAME}: 12 pieces, ${rawBytes} B of SVG stripped to ${keptBytes} B`);
